name: Deploy to EC2

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Execute remote SSH commands using key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.204.83.147
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v24.12.0/bin
            
            cd ~/cicd-demo
            git pull origin main
            npm install
            npm run build
            npm run start